name: Append updates after PR merge to reset

permissions:
  contents: write  # Allows the workflow to push commits

on:
  push:
    branches:
      - main  # Runs when something is pushed to main

jobs:
  append-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Ensure full history is available

      - name: Ensure log file exists
        run: |
          touch updates_log.txt  # Create if it doesn't exist

      - name: Append new updates to log file
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "---- Update from branch: $BRANCH_NAME ----" >> updates_log.txt
          cat "What's been added.txt" >> updates_log.txt
          echo "" >> updates_log.txt  # Add newline for formatting

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add updates_log.txt
          git commit -m "Appended updates from latest push"
          git push origin main
