name: Append updates after PR merge to reset

on:
  push:
    branches:
      - main

jobs:
  append-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the reset branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Ensure full history is available

      - name: Append PR’s "Updates/What's been added.txt"
        run: |
          echo "" >> "Updates/What's been added.txt"  # Add a newline for formatting
          cat "Updates/What's been added.txt" >> merged_updates.txt  # Save the new content
          mv merged_updates.txt "Updates/What's been added.txt"  # Replace original file

      - name: Commit and push changes to reset
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "Updates/What's been added.txt"
          git commit -m "Appended updates from latest push"
          git push origin main
